# Site settings
title: IHomer
tagline: thuis in IT
email: info@ihomer.nl
description: >
  IHomer is een IT-bedrijf met als motto 'een beetje anders, een groot verschil'. Vanuit de kracht van individuen,
  gebruik makend van de mogelijkheden die ICT biedt en rekening houdend met de maatschappij is een nieuwe en
  inspirerende werkvorm ontstaan.
baseurl: ""
url: https://ihomer.github.io # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
highlighter: pygments
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .editorconfig
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-coffeescript
